# Generated by Django 4.2.4 on 2023-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.BigIntegerField(default=None, null=True)),
                ('block_timestamp', models.CharField(default=None, max_length=255, null=True)),
                ('nonce', models.BigIntegerField(default=None, null=True)),
                ('previous_block_hash', models.CharField(default=None, max_length=255, null=True)),
                ('node', models.IntegerField(default=None, null=True)),
                ('temp', models.IntegerField(default=None, null=True)),
                ('trans_timestamp', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
