# Generated by Django 4.2.4 on 2023-09-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='BlockchainTransactions',
        ),
    ]
