# Generated by Django 4.2.4 on 2023-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_rename_blockchain_blockchaintransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchaintransactions',
            name='node',
        ),
        migrations.RemoveField(
            model_name='blockchaintransactions',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='blockchaintransactions',
            name='trans_timestamp',
        ),
        migrations.AddField(
            model_name='blockchaintransactions',
            name='transactions',
            field=models.JSONField(null=True),
        ),
    ]
