# Generated by Django 4.2.4 on 2023-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_remove_blockchaintransactions_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransactions',
            name='last_trans_timestamp',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
